services:
  mysql:
    image: 'mysql:latest'
    container_name: courses-platform-api-mysql-1
    environment:
      MYSQL_DATABASE: courses-platform-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '3306:3306' # HostPort:ContainerPort
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
